//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ImportJsonLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImportJsonLocations"]));
            }
            set {
                this["ImportJsonLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DogovorjenaMočBlok1 {
            get {
                return ((double)(this["DogovorjenaMočBlok1"]));
            }
            set {
                this["DogovorjenaMočBlok1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DogovorjenaMočBlok2 {
            get {
                return ((double)(this["DogovorjenaMočBlok2"]));
            }
            set {
                this["DogovorjenaMočBlok2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DogovorjenaMočBlok3 {
            get {
                return ((double)(this["DogovorjenaMočBlok3"]));
            }
            set {
                this["DogovorjenaMočBlok3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DogovorjenaMočBlok4 {
            get {
                return ((double)(this["DogovorjenaMočBlok4"]));
            }
            set {
                this["DogovorjenaMočBlok4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DogovorjenaMočBlok5 {
            get {
                return ((double)(this["DogovorjenaMočBlok5"]));
            }
            set {
                this["DogovorjenaMočBlok5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DatumOd {
            get {
                return ((global::System.DateTime)(this["DatumOd"]));
            }
            set {
                this["DatumOd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DatumDo {
            get {
                return ((global::System.DateTime)(this["DatumDo"]));
            }
            set {
                this["DatumDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MočBlokOd {
            get {
                return ((double)(this["MočBlokOd"]));
            }
            set {
                this["MočBlokOd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MočBlokDo {
            get {
                return ((double)(this["MočBlokDo"]));
            }
            set {
                this["MočBlokDo"] = value;
            }
        }
    }
}
